baseURL = 'https://senchpimy.github.io/'
languageCode = 'en-us'
title = 'Senchpimy'

[menu]
[[menu.main]]
    name = 'Entradas'
    pageRef = 'entradas'
    weight = 10
[[menu.main]]
    name = 'Archivos'
    pageRef = 'archivos'
    weight = 20
[[menu.main]]
    name = 'Wallpaper'
    pageRef = 'wallpapers'
    weight = 30
[[menu.main]]
    name = 'Problemas'
    pageRef = 'problemas'
    weight = 50

[markup.goldmark.renderer]
unsafe = true
